version: "2.4"

services:
  web-server:
    build:
      context: .
      dockerfile: ./dockerfile-web-server
    volumes:
    - ./web-server:/app
    ports:
    - 8080:8080
    mem_limit: 1g
    cpus: 1
  
  web-client:
    build:
      context: .
      dockerfile: ./dockerfile-web-client
    volumes:
    - ./web-client:/app
    mem_limit: 1g
    cpus: 1